files:
  - source: /
    ignore_settings: 1
    ignore:
      - /form
      - /l
      - /public_html
      - /ko
      - /zh-Hans
      - /zh-Hant
      - /images
      - /assets
      - sitemap.xml
    translation: /%two_letters_code%/%original_file_name%
