name: Deploy chinese website
on:
  push:
    branches:
    - suhee/China-mxcwebsite

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzr --delete
        path: .
        remote_path: /home/ubuntu/reverse-proxy/data/mxc-website
        remote_host: mxcchengdu.com
        remote_user: ubuntu
        remote_key: ${{ secrets.DEPLOY_KEY }}
