name: Running link checker

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lc
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r . 

    - name: Archive linkchecker results
      uses: actions/upload-artifact@v2
      with:
        name: link-checker-results
        path: link-checker/out.md
